trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  support_netstandard20: true
  support_netstandard21: true
  support_netcoreapp21: true
  support_netcoreapp31: true
  support_net5_0: true

resources:
  repositories:
    - repository: buildscripts
      type: github
      name: Sannel/Sannel.House.BuildScripts

jobs:
- template: tasks/Library.yaml@buildscripts  # Template reference